#include "ReversiConstant.h"

// 全ての有効な座標の定義
const reversi::ReversiConstant::POSITION reversi::ReversiConstant::POSITIONS[reversi::ReversiConstant::POSITION_SIZE] = {
	reversi::ReversiConstant::POSITION::A1, reversi::ReversiConstant::POSITION::B1, reversi::ReversiConstant::POSITION::C1, reversi::ReversiConstant::POSITION::D1, reversi::ReversiConstant::POSITION::E1, reversi::ReversiConstant::POSITION::F1, reversi::ReversiConstant::POSITION::G1, reversi::ReversiConstant::POSITION::H1,
	reversi::ReversiConstant::POSITION::A2, reversi::ReversiConstant::POSITION::B2, reversi::ReversiConstant::POSITION::C2, reversi::ReversiConstant::POSITION::D2, reversi::ReversiConstant::POSITION::E2, reversi::ReversiConstant::POSITION::F2, reversi::ReversiConstant::POSITION::G2, reversi::ReversiConstant::POSITION::H2,
	reversi::ReversiConstant::POSITION::A3, reversi::ReversiConstant::POSITION::B3, reversi::ReversiConstant::POSITION::C3, reversi::ReversiConstant::POSITION::D3, reversi::ReversiConstant::POSITION::E3, reversi::ReversiConstant::POSITION::F3, reversi::ReversiConstant::POSITION::G3, reversi::ReversiConstant::POSITION::H3,
	reversi::ReversiConstant::POSITION::A4, reversi::ReversiConstant::POSITION::B4, reversi::ReversiConstant::POSITION::C4, reversi::ReversiConstant::POSITION::D4, reversi::ReversiConstant::POSITION::E4, reversi::ReversiConstant::POSITION::F4, reversi::ReversiConstant::POSITION::G4, reversi::ReversiConstant::POSITION::H4,
	reversi::ReversiConstant::POSITION::A5, reversi::ReversiConstant::POSITION::B5, reversi::ReversiConstant::POSITION::C5, reversi::ReversiConstant::POSITION::D5, reversi::ReversiConstant::POSITION::E5, reversi::ReversiConstant::POSITION::F5, reversi::ReversiConstant::POSITION::G5, reversi::ReversiConstant::POSITION::H5,
	reversi::ReversiConstant::POSITION::A6, reversi::ReversiConstant::POSITION::B6, reversi::ReversiConstant::POSITION::C6, reversi::ReversiConstant::POSITION::D6, reversi::ReversiConstant::POSITION::E6, reversi::ReversiConstant::POSITION::F6, reversi::ReversiConstant::POSITION::G6, reversi::ReversiConstant::POSITION::H6,
	reversi::ReversiConstant::POSITION::A7, reversi::ReversiConstant::POSITION::B7, reversi::ReversiConstant::POSITION::C7, reversi::ReversiConstant::POSITION::D7, reversi::ReversiConstant::POSITION::E7, reversi::ReversiConstant::POSITION::F7, reversi::ReversiConstant::POSITION::G7, reversi::ReversiConstant::POSITION::H7,
	reversi::ReversiConstant::POSITION::A8, reversi::ReversiConstant::POSITION::B8, reversi::ReversiConstant::POSITION::C8, reversi::ReversiConstant::POSITION::D8, reversi::ReversiConstant::POSITION::E8, reversi::ReversiConstant::POSITION::F8, reversi::ReversiConstant::POSITION::G8, reversi::ReversiConstant::POSITION::H8
};

const reversi::ReversiConstant::POSITION reversi::ReversiConstant::POSITION_HORIZONTALS[reversi::ReversiConstant::BOARD_SIZE_Y][reversi::ReversiConstant::BOARD_SIZE_X] = {
	{ reversi::ReversiConstant::POSITION::A1, reversi::ReversiConstant::POSITION::B1, reversi::ReversiConstant::POSITION::C1, reversi::ReversiConstant::POSITION::D1, reversi::ReversiConstant::POSITION::E1, reversi::ReversiConstant::POSITION::F1, reversi::ReversiConstant::POSITION::G1, reversi::ReversiConstant::POSITION::H1 },
	{ reversi::ReversiConstant::POSITION::A2, reversi::ReversiConstant::POSITION::B2, reversi::ReversiConstant::POSITION::C2, reversi::ReversiConstant::POSITION::D2, reversi::ReversiConstant::POSITION::E2, reversi::ReversiConstant::POSITION::F2, reversi::ReversiConstant::POSITION::G2, reversi::ReversiConstant::POSITION::H2 },
	{ reversi::ReversiConstant::POSITION::A3, reversi::ReversiConstant::POSITION::B3, reversi::ReversiConstant::POSITION::C3, reversi::ReversiConstant::POSITION::D3, reversi::ReversiConstant::POSITION::E3, reversi::ReversiConstant::POSITION::F3, reversi::ReversiConstant::POSITION::G3, reversi::ReversiConstant::POSITION::H3 },
	{ reversi::ReversiConstant::POSITION::A4, reversi::ReversiConstant::POSITION::B4, reversi::ReversiConstant::POSITION::C4, reversi::ReversiConstant::POSITION::D4, reversi::ReversiConstant::POSITION::E4, reversi::ReversiConstant::POSITION::F4, reversi::ReversiConstant::POSITION::G4, reversi::ReversiConstant::POSITION::H4 },
	{ reversi::ReversiConstant::POSITION::A5, reversi::ReversiConstant::POSITION::B5, reversi::ReversiConstant::POSITION::C5, reversi::ReversiConstant::POSITION::D5, reversi::ReversiConstant::POSITION::E5, reversi::ReversiConstant::POSITION::F5, reversi::ReversiConstant::POSITION::G5, reversi::ReversiConstant::POSITION::H5 },
	{ reversi::ReversiConstant::POSITION::A6, reversi::ReversiConstant::POSITION::B6, reversi::ReversiConstant::POSITION::C6, reversi::ReversiConstant::POSITION::D6, reversi::ReversiConstant::POSITION::E6, reversi::ReversiConstant::POSITION::F6, reversi::ReversiConstant::POSITION::G6, reversi::ReversiConstant::POSITION::H6 },
	{ reversi::ReversiConstant::POSITION::A7, reversi::ReversiConstant::POSITION::B7, reversi::ReversiConstant::POSITION::C7, reversi::ReversiConstant::POSITION::D7, reversi::ReversiConstant::POSITION::E7, reversi::ReversiConstant::POSITION::F7, reversi::ReversiConstant::POSITION::G7, reversi::ReversiConstant::POSITION::H7 },
	{ reversi::ReversiConstant::POSITION::A8, reversi::ReversiConstant::POSITION::B8, reversi::ReversiConstant::POSITION::C8, reversi::ReversiConstant::POSITION::D8, reversi::ReversiConstant::POSITION::E8, reversi::ReversiConstant::POSITION::F8, reversi::ReversiConstant::POSITION::G8, reversi::ReversiConstant::POSITION::H8 }

};
